version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'frontend'
    ports:
      - '4000:4000'
    volumes:
      - ./frontend:/app
    stdin_open: true

  backend:
    restart: always
    build: .
    environment:
      FLASK_APP: 'app.py'
      FLASK_DEBUG: 1
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
