version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  app:
    restart: always
    build: .
    environment:
      FLASK_APP: "app.py"
      FLASK_DEBUG: 1
    container_name: "backend"
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
