version: '3.9'
services:
  app:
    restart: always
    build: .
    environment:
      FLASK_APP: 'app.py'
      FLASK_DEBUG: 1
    container_name: 'app'
    tty: true
    ports:
      - '3000:5000'
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
